version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8.10.0
      - image: redis:3.2.9
    environment:
      COVERALLS_REPO_TOKEN: "fsVv3ZKZ4rZeUPKHC1IOycaEobCSR3k1c"
    working_directory: ~/stellar
    steps:
          - checkout
          - run:
              name: Update yarn
              command: 'sudo npm install -g yarn@1.3.2'
          - restore_cache:
              key: yarn-cache-{{ checksum "yarn.lock" }}
          - run: 
              name: Install Dependencies
              command: yarn
          - run:
              name: Run Tests
              command: yarn run coverage
          - store_test_results:
              path: ./.artifacts/test_results
          - store_test_results:
              path: ./.artifacts/lint_results
          - run:
              name: Uploading coverage to coveralls...
              command: cat ./.artifacts/coverage/*/lcov.info | ./node_modules/.bin/coveralls
          - save_cache:
              key: yarn-cache-{{ checksum "yarn.lock" }}
              paths:
                - node_modules
        