const MINUTE_1 = 60 * 1000; // 1 minute
const DEFAULT_INTERVAL = 15 * MINUTE_1; // 15 minutes
const JOB_TIMEOUT = 5 * MINUTE_1;
const TWO_WEEKS = 14 * 24 * 60 * MINUTE_1;

export { MINUTE_1, DEFAULT_INTERVAL, JOB_TIMEOUT, TWO_WEEKS };
